const cat = {
	home: {
		title: "Inici",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehícle",
			bike: "Bici",
			favs: "Preferits",
			highlight: "Destacats",
		}, 
		searchBar: "Buscar:",
	}, 
	settings: {
		title: "Configuració",
		subtitle: "Benvingut a la configuració",
		logOut: "Tancar sessió",
		setEN: "Anglès",
		setCAT: "Català",
		setES: "Espanyol",
		deleteAccount: "Esborrar el teu compte",
		deleteAccountTitle: "Estas segur de que vols eliminar el teu compte?",
		deleteAccountSubtitle: "Aquesta acció no és reversible i perdràs accés futur a l'aplicació.",
		setLanguage: "Escollir idioma",
		confirmDeleteAccount: "Per eliminar el teu compte cal escriure a sota el teu nom d'usuari",
	}, 
	signIn: {
		title: "Iniciar sessió",
		form: {
			enterCredentials: "Introdueix els credencials",
		}, 
		otherSocial: "O inicia sessió amb",
		pwdOrEmailMessage: "Hi ha un error amb el email o la contrasenya",
		emptyFieldMessage: "Siusplau ompli tots els camps",
		noAccount: "No tens compte?",
		enterEmail: "Introdueix el teu email",
		enterPassword: "Introdueix la teva contrasenya",
	}, 
	signUp: {
		title: "Registrar-se",
		form: {
			enterCredentials: "Introdueix els credencials",
			email: "Email:",
			password: "Contrasenya:",
			name: "Nom:",
		}, 
		goToSignIn: "Anar a Inciar sessió",
		alreadyAccount: "Ja tens compte?",
		enterEmail: "Introdueix el teu email",
		enterPassword: "Introdueix la teva contrasenya",
		enterName: "Introdueix el teu nom",
	}, 
	miscelaneus: {
		loading: "Carregant...",
		cancel: "Cancel·lar",
		back: "Enrere",
		exit: "Sortir",
		accept: "Acceptar",
		delete: "Eliminar",
		vehicleWord: "vehicle",
	}, 
	vehicleConfig: {
		title: "Configuració del vehicle",
		vehicleBrand: "Marca del vehicle",
		vehicleBrandPlaceholder: "Introdueix la marca",
		vehicleModel: "Model del vehícle",
		vehicleModelPlaceholder: "Introdueix el model",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introdueix la matrícula",
		vehicleColor: "Color del vehicle",
		vehicleNickname: "Sobrenom del vehicle",
		vehicleNicknamePlaceholder: "Introdueix el sobrenom",
		continue: "Continua",
		notEV: "No tens un VE?",
		cancel: "Cancel·lar",
		skip: "Salta",
		customize: "Personalitza el teu",
	}, 
	profile: {
		yourVehicle: "El teu garatge",
		changeVehicle: "Llisca per canviar el teu vehicle per defecte",
		title: "Perfil",
		vehicleNotDef: "Vehicle no definit",
		addNewVehicle: "Afegeix un vehicle",
		saveChanges: "Desa els canvis",
		editProfile: "Edita el teu perfil",
	}, 
	carInfoItem: {
		nickname: "Sobrenom:",
		numberPlate: "Matricula:",
	}, 
	drawer: {
		home: "Inici",
		profile: "Perfil",
		settings: "Configuració",
		tellAFriend: "Comparteix amb un amic!",
		logOut: "Tancar sessió",
		shareMessage: "Descobreix EcoRoads | Una aplicació per a planejar els teus viatges 'Eco-Friendly' de forma eficient.",
		achievements: "Assoliments",
		help: "Ajuda",
	}, 
	locationInfo: {
		mechanical: "Mecàniques",
		electrical: "Elèctriques",
		parking: "Aparcaments",
		getThere: "Porta-m'hi!",
		likesNumber: "M'agrades",
		reportsNumber: "Incidències",
		report: "Reportar",
		pollutionLevel: "Nivell de contaminació",
		shareStation: "Compartir estació",
		shareMessage: "Ei! Fes-li una ullada a",
		shareMessage2: ". Ens veiem allà!",
	}, 
	uploadImage: {
		editImage: "Editar Imatge",
		uploadImage: "Afegir Imatge",
	}, 
	achievementScreen: {
		subtitle: "Els teus assoliments:",
		shareMessage: "He completat aquest assoliment a EcoRoads. Fes-li una ullada: ",
		Achievements: {
			tellAFriendTitle: "",
			tellAFriendDescription: "",
			firstRouteTitle: "",
			firstRouteDescription: "",
			firstSearchTitle: "",
			firstSearchDescription: "",
			shareAStationTitle: "",
			shareStationDescription: "",
			setStationAsFavouriteTitle: "",
			setStationAsFavouriteDescription: "",
			likeAStationTitle: "",
			likeAStationDescription: "",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Si us plau emplena tots els camps",
			OSversion: "Sistema Operatiu",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalls de la consulta",
			title: "Pantalla d'Incidències",
			mobilepl: "Tipus de dispositiu",
			type: "Tipus de Incidència",
			smartphone: "Smartphone",
			tablet: "Tauleta",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "Ajuda general",
			featureRequest: "Sol·licitud de funcionalitat",
			feedback: "Comentari",
		}, 
		send: "Enviar",
		reportStation: {
			title: "Reportar una estació",
			subtitle: "",
			placeholder: "Descripció del problema",
			poorCondition: "Males condicions",
			badInformation: "Informació errònia",
			dislike: "No m'agrada",
		}, 
	}, 
	achievementToast: {
		title: "Assoliment completat!",
	}, 
	reportToast: {
		title: "Canvis guardats",
		message: "S'ha actualitzat correctament el teu perfil.",
	}
}
export{ cat }