const cat = {
	home: {
		title: "Inici",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehícle",
			bike: "Bici",
			favs: "Preferits",
			highlight: "Destacats",
		}, 
		searchBar: "Buscar:",
	}, 
	settings: {
		title: "Configuració",
		subtitle: "Benvingut a la configuració",
		logOut: "Tancar sessió",
		setEN: "Idioma Anglès",
		setCAT: "Idioma Català",
		setES: "Idioma Espanyol",
		deleteAccount: "Esborrar el teu compte",
		deleteAccountTitle: "Estas segur de que vols eliminar el teu compte?",
		deleteAccountSubtitle: "Aquesta acció no és reversible i perdràs accés futur a l'aplicació.",
	}, 
	signIn: {
		title: "Iniciar sessió",
		form: {
			enterCredentials: "Introdueix els credencials",
		}, 
		otherSocial: "O inicia sessió amb",
		pwdOrEmailMessage: "Hi ha un error amb el email o la contrasenya",
		emptyFieldMessage: "Siusplau ompli tots els camps",
		noAccount: "No tens compte?",
	}, 
	signUp: {
		title: "Registrar-se",
		form: {
			enterCredentials: "Introdueix els credencials",
			email: "Email:",
			password: "Contrasenya:",
			name: "Nom:",
		}, 
		goToSignIn: "Anar a Inciar sessió",
	}, 
	miscelaneus: {
		loading: "Carregant...",
		cancel: "Cancel·lar",
		back: "Enrere",
		exit: "Sortir",
		accept: "Acceptar",
	}, 
	vehicleConfig: {
		title: "Configuració del vehicle",
		vehicleBrand: "Marca del vehicle",
		vehicleBrandPlaceholder: "Introdueix la marca",
		vehicleModel: "Model del vehícle",
		vehicleModelPlaceholder: "Introdueix el model",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introdueix la matrícula",
		vehicleColor: "Color del vehicle",
		vehicleNickname: "Sobrenom del vehicle",
		vehicleNicknamePlaceholder: "Introdueix el sobrenom",
		continue: "Continua",
		notEV: "No tens un VE?",
		cancel: "Cancel·lar",
		skip: "Salta",
	}, 
	profile: {
		yourVehicle: "Informació dels teus vehicles",
		changeVehicle: "Llisca per canviar el teu vehicle per defecte",
		title: "Perfil",
		vehicleNotDef: "Vehicle no definit",
		addNewVehicle: "Afegeix un vehicle",
		saveChanges: "Desa els canvis",
		editProfile: "Edita el teu perfil",
	}, 
	carInfoItem: {
		nickname: "Sobrenom:",
		numberPlate: "Matricula:",
	}, 
	drawer: {
		home: "Inici",
		profile: "Perfil",
		settings: "Configuració",
		tellAFriend: "Comparteix amb un amic!",
		logOut: "Tancar sessió",
		shareMessage: "Descobreix EcoRoads | Una aplicació per a planejar els teus viatges 'Eco-Friendly' de forma eficient.",
		achievements: "Assoliments",
	}, 
	locationInfo: {
		mechanical: "Mecàniques",
		electrical: "Elèctriques",
		parking: "Aparcaments",
		getThere: "Porta-m'hi!",
		likesNumber: "M'agrades",
		reportsNumber: "Incidències",
		report: "Reportar",
	}, 
	uploadImage: {
		editImage: "Editar Imatge",
		uploadImage: "Afegir Imatge",
	}, 
	report: {
		reportStation: {
			title: "Reportar una estació",
			subtitle: "",
			placeholder: "Descripció del problema",
			poorCondition: "Males condicions",
			badInformation: "Informació errònia",
			dislike: "No m'agrada",
		}, 
		send: "Enviar",
	}, 
	achievementScreen: {
		subtitle: "Els teus assoliments:",
		shareMessage: "He completat aquest assoliment a EcoRoads. Fes-li una ullada: ",
	}, 
	reportApp: {
		ReportApplicationScreen: {
			fillfields: "Si us plau emplena tots els camps",
			OSversion: "Quina versió del SO esta fent servir?",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalls de la consulta",
			title: "Pantalla d'Incidències",
			mobilepl: "Desde quina plataforma mòvil està fent la consulta?",
			type: "Tipus de Incidència",
		}, 
	}, 
	achievementToast: {
		title: "Assoliment completat!",
	}, 
	reportToast: {
		title: "Canvis guardats",
		message: "S'ha actualitzat correctament el teu perfil.",
	}, 
	routeInfo: {
	}
}
export{ cat }