const en = {
	home: {
		title: "Home",
		bottomBar: {
			map: "Map",
			vehicle: "Vehicle",
			bike: "Bike",
			highlight: "Highlight",
		}, 
		searchBar: "Search:",
	}, 
	settings: {
		title: "Settings",
		subtitle: "Welcome to settings",
		logOut: "Log Out",
		setEN: "English language",
		setCAT: "Catalan language",
		setES: "Spanish language",
		deleteAccount: "Delete your account",
		deleteAccountTitle: "Are you sure you want to delete you account?",
		deleteAccountSubtitle: "This action is not reversible and you will lose future access to the app.",
	}, 
	signIn: {
		title: "Log In",
		form: {
			enterCredentials: "Enter your credentials",
		}, 
		otherSocial: "Or Log In with",
		pwdOrEmailMessage: "There is an error with your password or email",
		emptyFieldMessage: "Please fill in all fields",
		noAccount: "Haven't got an account?",
	}, 
	signUp: {
		title: "Sign Up",
		form: {
			enterCredentials: "Enter your credentials",
			email: "Email:",
			password: "Password:",
			name: "Name:",
		}, 
		goToSignIn: "Go to Log In",
	}, 
	miscelaneus: {
		loading: "Loading...",
		cancel: "Cancel",
		accept: "Accept",
	}, 
	vehicleConfig: {
		title: "Vehicle configuration",
		vehicleBrand: "Vehicle brand",
		vehicleBrandPlaceholder: "Car's brand here",
		vehicleModel: "Vehicle model",
		vehicleModelPlaceholder: "Car's model here",
		vehicleNumPlate: "Number plate",
		vehicleNumPlatePlaceholder: "Car's number plate here",
		vehicleColor: "Vehicle Color",
		vehicleNickname: "Vehicle Nickname",
		vehicleNicknamePlaceholder: "Car's nickname here",
		continue: "Continue",
		notEV: "Don't have an EV?",
		cancel: "Cancel",
		skip: "Skip",
	}, 
	profile: {
		yourVehicle: "Your vehicles information",
		title: "Profile",
		vehicleNotDef: "Vehicle not defined yet",
		addNewVehicle: "Add a new vehicle",
		saveChanges: "Save changes",
		editProfile: "Edit your profile",
	}, 
	carInfoItem: {
		nickname: "Nickname:",
		numberPlate: "Number Plate:",
	}, 
	drawer: {
		home: "Home",
		profile: "Profile",
		settings: "Settings",
		tellAFriend: "Share it with a friend!",
		logOut: "Log Out",
		shareMessage: "Check EcoRoads out | An app to plan your Eco-Friendly trips efficiently.",
	}, 
	locationInfo: {
		mechanical: "Mechanical",
		electrical: "Electrical",
		parking: "Parkings",
		getThere: "Get there!",
		report: "Report",
	}, 
	uploadImage: {
		editImage: "Edit Image",
		uploadImage: "Upload Image",
	}, 
	report: {
		reportStation: {
			title: "Report a Station",
			subtitle: "",
			placeholder: "Issue description",
			poorCondition: "Poor conditions",
			badInformation: "Incorrect Info",
			dislike: "Dislike",
		}, 
		send: "Send",
	}
}
export{ en }