const en = {
	home: {
		title: "Home",
		bottomBar: {
			map: "Map",
			vehicle: "Vehicle",
			bike: "Bike",
			favs: "Favs",
			highlight: "Highlight",
		}, 
		searchBar: "Search:",
	}, 
	settings: {
		title: "Settings",
		subtitle: "Welcome to settings",
		logOut: "Log Out",
		setEN: "English",
		setCAT: "Catalan",
		setES: "Spanish",
		deleteAccount: "Delete your account",
		deleteAccountTitle: "Are you sure you want to delete you account?",
		deleteAccountSubtitle: "This action is not reversible and you will lose future access to the app.",
		setLanguage: "Set the language",
		confirmDeleteAccount: "To delete your account you must write down below your userame",
	}, 
	signIn: {
		title: "Log In",
		form: {
			enterCredentials: "Enter your credentials",
		}, 
		otherSocial: "Or Log In with",
		pwdOrEmailMessage: "There is an error with your password or email",
		emptyFieldMessage: "Please fill in all fields",
		noAccount: "Haven't got an account?",
		enterEmail: "Enter your email",
		enterPassword: "Enter your password",
	}, 
	signUp: {
		title: "Sign Up",
		form: {
			enterCredentials: "Enter your credentials",
			email: "Email:",
			password: "Password:",
			name: "Name:",
		}, 
		goToSignIn: "Go to Log In",
		alreadyAccount: "Already have an account?",
		enterEmail: "Enter your email",
		enterPassword: "Enter your password",
		enterName: "Enter your name",
	}, 
	miscelaneus: {
		loading: "Loading...",
		cancel: "Cancel",
		back: "Back",
		exit: "Exit",
		accept: "Accept",
		delete: "Delete",
		vehicleWord: "vehicle",
	}, 
	vehicleConfig: {
		title: "Vehicle configuration",
		vehicleBrand: "Vehicle brand",
		vehicleBrandPlaceholder: "Car's brand here",
		vehicleModel: "Vehicle model",
		vehicleModelPlaceholder: "Car's model here",
		vehicleNumPlate: "Number plate",
		vehicleNumPlatePlaceholder: "Car's number plate here",
		vehicleColor: "Vehicle Color",
		vehicleNickname: "Vehicle Nickname",
		vehicleNicknamePlaceholder: "Car's nickname here",
		continue: "Continue",
		notEV: "Don't have an EV?",
		cancel: "Cancel",
		skip: "Skip",
		customize: "Customize your",
	}, 
	profile: {
		yourVehicle: "Your Garage",
		changeVehicle: "Swipe to change your default vehicle",
		title: "Profile",
		vehicleNotDef: "Vehicle not defined yet",
		addNewVehicle: "Add a new vehicle",
		saveChanges: "Save changes",
		editProfile: "Edit your profile",
	}, 
	carInfoItem: {
		nickname: "Nickname:",
		numberPlate: "Number Plate:",
	}, 
	drawer: {
		home: "Home",
		profile: "Profile",
		settings: "Settings",
		tellAFriend: "Share it with a friend!",
		logOut: "Log Out",
		shareMessage: "Check EcoRoads out | An app to plan your Eco-Friendly trips efficiently.",
		achievements: "Achievements",
		help: "Help",
	}, 
	locationInfo: {
		mechanical: "Mechanical",
		electrical: "Electrical",
		parking: "Parkings",
		getThere: "Get there!",
		likesNumber: "Likes",
		reportsNumber: "Reports",
		report: "Report",
		pollutionLevel: "Pollution level",
		shareStation: "Share station",
		shareMessage: "Hey! Check out",
		shareMessage2: "station. Meet you there!",
	}, 
	uploadImage: {
		editImage: "Edit Image",
		uploadImage: "Upload Image",
	}, 
	achievementScreen: {
		subtitle: "Your achievements:",
		shareMessage: "I have completed this achievement on EcoRoads. Check it out: ",
		Achievements: {
			tellAFriendTitle: "Tell a friend",
			tellAFriendDescription: "",
			firstRouteTitle: "",
			firstRouteDescription: "",
			firstSearchTitle: "",
			firstSearchDescription: "",
			shareAStationTitle: "",
			shareStationDescription: "",
			setStationAsFavouriteTitle: "",
			setStationAsFavouriteDescription: "",
			likeAStationTitle: "",
			likeAStationDescription: "",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Please fill in all fields",
			OSversion: "Operating System",
			subjectinquiry: "Subject of Inquiry",
			detailsinquiry: "Details of Inquiry",
			title: "Report Screen",
			mobilepl: "Device type",
			type: "Type of Report ",
			smartphone: "Smartphone",
			tablet: "Tablet",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "General help",
			featureRequest: "Feature request",
			feedback: "Feedback",
		}, 
		send: "Send",
		reportStation: {
			title: "Report a Station",
			subtitle: "",
			placeholder: "Issue description",
			poorCondition: "Poor conditions",
			badInformation: "Incorrect Info",
			dislike: "Dislike",
		}, 
	}, 
	achievementToast: {
		title: "Achievement completed!",
	}, 
	reportToast: {
		title: "Changes saved",
		message: "Your profile was updated successfully.",
	}
}
export{ en }