const es = {
	home: {
		title: "Inicio",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehículo",
			bike: "Bici",
			favs: "Favoritos",
			highlight: "Destacados",
		}, 
		searchBar: "Buscar:",
	}, 
	settings: {
		title: "Ajustes",
		subtitle: "Bienvenido a los ajustes",
		logOut: "Cerrar sesión",
		setEN: "Inglés",
		setCAT: "Catalán",
		setES: "Español",
		deleteAccount: "Borrar tu cuenta",
		deleteAccountTitle: "¿Estás seguro de que quieres eliminar tu cuenta?",
		deleteAccountSubtitle: "Esta acción no es reversible y perderás todo acceso futuro a la aplicación.",
		setLanguage: "Escoger idioma",
		confirmDeleteAccount: "Para eliminar tu cuenta debes escribir debajo tu nombre de usuario",
	}, 
	signIn: {
		title: "Iniciar sesión",
		form: {
			enterCredentials: "Ingrese sus credenciales",
		}, 
		otherSocial: "O inicie sesión con",
		pwdOrEmailMessage: "Hay un error con el email o contraseña",
		emptyFieldMessage: "Porfavor rellene todos los campos",
		noAccount: "¿No tiene una cuenta?",
	}, 
	signUp: {
		title: "Registrarse",
		form: {
			enterCredentials: "Ingrese sus credenciales",
			email: "Email:",
			password: "Contraseña:",
			name: "Nombre:",
		}, 
		goToSignIn: "Ir a Iniciar sesión",
	}, 
	miscelaneus: {
		loading: "Cargando...",
		cancel: "Cancelar",
		back: "Atrás",
		exit: "Salir",
		accept: "Aceptar",
		delete: "Eliminar",
	}, 
	vehicleConfig: {
		title: "Configuracion del vehículo",
		vehicleBrand: "Marca del vehículo",
		vehicleBrandPlaceholder: "Introduce la marca",
		vehicleModel: "Modelo del vehículo",
		vehicleModelPlaceholder: "Introduce el modelo",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introduce la matrícula",
		vehicleColor: "Color del vehículo",
		vehicleNickname: "Apodo del vehículo",
		vehicleNicknamePlaceholder: "Introduce el apodo",
		continue: "Continuar",
		notEV: "¿No tienes un VE?",
		cancel: "Cancelar",
		skip: "Saltar",
	}, 
	profile: {
		yourVehicle: "Tu garaje",
		changeVehicle: "Desliza para cambiar tu vehículo por defecto",
		title: "Perfil",
		vehicleNotDef: "Vehículo no definido",
		addNewVehicle: "Añade un vehículo",
		saveChanges: "Guardar cambios",
		editProfile: "Edita tu perfil",
	}, 
	carInfoItem: {
		nickname: "Apodo:",
		numberPlate: "Matricula:",
	}, 
	drawer: {
		home: "Inicio",
		profile: "Perfil",
		settings: "Ajustes",
		tellAFriend: "¡Compártelo con un amigo!",
		logOut: "Cerrar sesión",
		shareMessage: "Descubre EcoRoads | Una aplicación para planear tus viajes 'Eco-Friendly' de forma eficiente.",
		achievements: "Logros",
		help: "Ayuda",
	}, 
	locationInfo: {
		mechanical: "Mecanicas",
		electrical: "Electricas",
		parking: "Estacionamientos",
		getThere: "¡Llévame!",
		likesNumber: "Me gustas",
		reportsNumber: "Reportes",
		report: "Reportar",
		pollutionLevel: "Nivel de contaminación",
		shareStation: "Compartir estación",
		shareMessage: "Ey! Echa un vistazo a",
		shareMessage2: ". Nos vemos ahí!",
	}, 
	uploadImage: {
		editImage: "Editar Imagen",
		uploadImage: "Añadir Imagen",
	}, 
	achievementScreen: {
		subtitle: "Tus logros:",
		shareMessage: "He completado este logro en EcoRoads. Échale un vistazo: ",
		Achievements: {
			tellAFriendTitle: "Díselo a un amigo",
			tellAFriendDescription: "Descripción de un logro, probando comas.",
			firstRouteTitle: "Tu primera ruta",
			firstRouteDescription: "Descripción de un logro, probando comas.",
			firstSearchTitle: "Tu primera búsqueda",
			firstSearchDescription: "Descripción de un logro, probando comas.",
			shareAStationTitle: "Comparte una estación",
			shareStationDescription: "Descripción de un logro, probando comas.",
			setStationAsFavouriteTitle: "Añade una estación a favoritos",
			setStationAsFavouriteDescription: "Descripción de un logro, probando comas.",
			likeAStationTitle: "Dále a Me gusta a una estación",
			likeAStationDescription: "Descripción de un logro, probando comas.",
		}, 
	}, 
	report: {
		ReportApplicationScreen: {
			fillfields: "Porfavor rellena todos los campos",
			OSversion: "Sistema Operativo",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalles de la consulta",
			title: "Pagina de Reporte",
			mobilepl: "Tipo de dispositivo",
			type: "Tipo de Reporte",
			smartphone: "Smartphone",
			tablet: "Tablet",
			ios: "iOS",
			android: "Android",
			bug: "Bug",
			generalHelp: "Ayuda general",
			featureRequest: "Solicitud de funcionalidad",
			feedback: "Comentario",
		}, 
		send: "Enviar",
		reportStation: {
			title: "Reportar una estación",
			subtitle: "",
			placeholder: "Descripción del problema",
			poorCondition: "Malas condiciones",
			badInformation: "Información erronea",
			dislike: "No me gusta",
		}, 
	}, 
	achievementToast: {
		title: "¡Logro completado!",
	}, 
	reportToast: {
		title: "Cambios guardados",
		message: "Tu perfil ha sido correctamente actualizado .",
	}
}
export{ es }