const es = {
	home: {
		title: "Inicio",
		bottomBar: {
			map: "Mapa",
			vehicle: "Vehículo",
			bike: "Bici",
			favs: "Favoritos",
			highlight: "Destacados",
		}, 
		searchBar: "Buscar:",
	}, 
	settings: {
		title: "Ajustes",
		subtitle: "Bienvenido a los ajustes",
		logOut: "Cerrar sesión",
		setEN: "Idioma Inglés",
		setCAT: "Idioma Catalán",
		setES: "Idioma Español",
		deleteAccount: "Borrar tu cuenta",
		deleteAccountTitle: "¿Estás seguro de que quieres eliminar tu cuenta?",
		deleteAccountSubtitle: "Esta acción no es reversible y perderás todo acceso futuro a la aplicación.",
	}, 
	signIn: {
		title: "Iniciar sesión",
		form: {
			enterCredentials: "Ingrese sus credenciales",
		}, 
		otherSocial: "O inicie sesión con",
		pwdOrEmailMessage: "Hay un error con el email o contraseña",
		emptyFieldMessage: "Porfavor rellene todos los campos",
		noAccount: "¿No tiene una cuenta?",
	}, 
	signUp: {
		title: "Registrarse",
		form: {
			enterCredentials: "Ingrese sus credenciales",
			email: "Email:",
			password: "Contraseña:",
			name: "Nombre:",
		}, 
		goToSignIn: "Ir a Iniciar sesión",
	}, 
	miscelaneus: {
		loading: "Cargando...",
		cancel: "Cancelar",
		back: "Atrás",
		exit: "Salir",
		accept: "Aceptar",
	}, 
	vehicleConfig: {
		title: "Configuracion del vehículo",
		vehicleBrand: "Marca del vehículo",
		vehicleBrandPlaceholder: "Introduce la marca",
		vehicleModel: "Modelo del vehículo",
		vehicleModelPlaceholder: "Introduce el modelo",
		vehicleNumPlate: "Matrícula",
		vehicleNumPlatePlaceholder: "Introduce la matrícula",
		vehicleColor: "Color del vehículo",
		vehicleNickname: "Apodo del vehículo",
		vehicleNicknamePlaceholder: "Introduce el apodo",
		continue: "Continuar",
		notEV: "¿No tienes un VE?",
		cancel: "Cancelar",
		skip: "Saltar",
	}, 
	profile: {
		yourVehicle: "Información de tus vehículos",
		title: "Perfil",
		vehicleNotDef: "Vehículo no definido",
		addNewVehicle: "Añade un vehículo",
		saveChanges: "Guardar cambios",
		editProfile: "Edita tu perfil",
		vehicleDef: "Elige tu vehículo por defecto",
	}, 
	carInfoItem: {
		nickname: "Apodo:",
		numberPlate: "Matricula:",
		default:"Vehículo predeterminado",
	}, 
	drawer: {
		home: "Inicio",
		profile: "Perfil",
		settings: "Ajustes",
		tellAFriend: "Compartelo con un amigo!",
		logOut: "Cerrar sesión",
		shareMessage: "Descubre EcoRoads | Una aplicación para planear tus viajes 'Eco-Friendly' de forma eficiente.",
		achievements: "Logros",
	}, 
	locationInfo: {
		mechanical: "Mecanicas",
		electrical: "Electricas",
		parking: "Estacionamientos",
		getThere: "¡Llévame!",
		likesNumber: "Me gustas",
		reportsNumber: "Reportes",
		report: "Reportar",
	}, 
	uploadImage: {
		editImage: "Editar Imagen",
		uploadImage: "Añadir Imagen",
	}, 
	report: {
		reportStation: {
			title: "Reportar una estación",
			subtitle: "",
			placeholder: "Descripción del problema",
			poorCondition: "Malas condiciones",
			badInformation: "Información erronea",
			dislike: "No me gusta",
		}, 
		send: "Enviar",
	}, 
	achievementScreen: {
		subtitle: "Tus logros:",
	}, 
	reportApp: {
		ReportApplicationScreen: {
			fillfields: "Porfavor rellena todos los campos",
			OSversion: "¿Qué versión del SO esta usando?",
			subjectinquiry: "Tema de consulta",
			detailsinquiry: "Detalles de la consulta",
			title: "Pagina de Reporte",
			mobilepl: "¿Desde que plataforma mobil estas haciendo la consulta?",
			type: "Tipo de Reporte",
		}
	}
}
export{ es }